theme: jekyll-theme-hacker
title: Welcome to MyLocalDev instructions page.
description: Gathering some instructions I find interesting. Trying to keep my version of tested instructions - Tested at the creation time. Feel free to bookmark this if needed
